### ISSUE TITLE
chore(electron-packager): use asar to combine node_modules into archive

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#15]
As of 1e2e52281250ed3e135322d669237c9378458566, the [`microdrop-builder/electron-packager.config.js`][1] configuration does *not* use `asar` to write `resources/app/node_modules` to an archive, but rather, stores the `node_modules` in their original form.

This slows down install/uninstall operations considerably due to the many thousands of files in the `node_modules` file hierarchy.  In addition, it seems like the deeply nested files in the `node_modules` hierarchy may cause an issue for creating/installing a Conda package containing a MicroDrop Electron executable build.

--------------------------------------------

# Proposed solution

Add `asar` configuration to [`microdrop-builder/electron-packager.config.js`][1] to add `node_modules` to an `asar` archive in the built Electron app.

[1]: https://github.com/sci-bots/microdrop-3/blob/1e2e52281250ed3e135322d669237c9378458566/microdrop-builder/electron-packager.config.js

**Comment by cfobel** [comment]
# Waiting on:

 - #20 chore(display): dynamically serve `display.html`
 - #21 chore(plugins.json): write dynamic plugins configuration to IndexDB

**Comment by Lucaszw** [comment]
Update: Both #20 and #21 are closed now.
