### ISSUE TITLE
feat(webcam): add method to choose webcam

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#16]
When running in Chrome, the webcam can be selected (or disabled) using the camera icon in the address bar:

![image](https://user-images.githubusercontent.com/823355/35988691-309f918a-0ccd-11e8-9c0b-8881d725ed35.png)

However, this is not currently available in the Electron app.

------------------------------------------

**We need to implement a mechanism to choose a webcam from those available, or disable the video feed.**

**Comment by Lucaszw** [comment]
Noticed the video isn't appearing in Electron windows (only browser). Reopening for now

**Comment by Lucaszw** [comment]
nvm. Need to ensure only one app pulling the video feed at a time
