### ISSUE TITLE
feat(device-ui): add method to pan the device display

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#17]
As of 7bae06b, the device UI supports zooming, but does not support panning.

Panning used to work by right-clicking (see [here][1]), but now right-click brings up the context menu.  Maybe we can use something like `<shift><right-click>`?  Perhaps it is possible to just disable the context menu behaviour while, e.g., `<shift>` is held?

**Comment by Lucaszw** [comment]
This would definitely be a nice feature. Possibly could use wheel-click for panning (or a disable context menu option)

**Comment by Lucaszw** [comment]
ab69f489d3551db6af72981a93242b8fe1e4578d
