### ISSUE TITLE
bug(electron-packager): spawn causes `ENOENT` exception

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#18]
# Set up

 1. Build Electron executable:

        yarn run packager

 2. Run built executable:

        cd packager\Microdrop-win32-ia32
        .\Microdrop.exe

# Observed behaviour  

 - The MicroDrop application is launched and works as expected :heavy_check_mark:
 - The following error is written to the console (although it doesn't seem to cause any issue) :x: :

```sh
Uncaught Error: spawn C:\Users\chris\Documents\GitHub\microdrop-3\microdrop-builder\packager\Microdrop-win32-ia32\Microdrop.exe ENOENT
```

**Comment by Lucaszw** [comment]
Assuming this is fixed, closing for now.
