### ISSUE TITLE
chore(plugins.json): write dynamic plugins configuration to IndexDB

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#21]
When running from a built Electron executable file with `node_modules` packaged in an Electron `asar` archive, writing `plugins.json` does not work as expected.

# Proposed fix
 
Write dynamic plugins configuration to IndexDB instead of to `plugins.json`.

**Comment by Lucaszw** [comment]
Fixed with a1c5f4fb47f8c3088460424029e9eaacc41a0f89
