### ISSUE TITLE
bug(electron-packager): error on launch of packaged exe

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#22]
When executing the packaged Electron executable from 816a53f5389cdc03852b9bcb804a057e34667227, I encounter the following error:

![image](https://user-images.githubusercontent.com/823355/36069327-56659a42-0eb5-11e8-88d0-5d9b62aee3d3.png)

This might be related to #19 ?

**Comment by cfobel** [comment]
**Note:** as a temporary workaround, I was able to launch MicroDrop add the `--help` argument, i.e.:
```
.\Microdrop.exe --help
```

**Comment by Lucaszw** [comment]
Fixed with 6971fbdfb083ad8ccf4eabfcb9e2bc5b5321fff3
