### ISSUE TITLE
feat(plugin): new schema plugin

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#31]
Add schema plugin to allow plugins to provide a json file defining one or more [jsonschema][1]s of the form:

```json
{"<schema name 1>": {... schema ...},
 "<schema name 2>": {... schema ...}}
```

--------------------------------------------------------------------

**The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).**

Schema plugin:

 -  **SHOULD** subscribe to plugin schema topics, e.g., `.../<plugin name>/state/__schemas__`
 - **MUST** display a property editor GUI grouping available schemas by `(schema name, plugin name)`:
   * e.g. tabs:
![image](https://user-images.githubusercontent.com/823355/36738553-bf8fafe6-1bab-11e8-912c-e9e0bea026e4.png)
   * or nested JSON editor:
![image](https://user-images.githubusercontent.com/823355/36738584-de231e84-1bab-11e8-9f7f-a0f2523984e7.png)
 - each schema **MAY** include flag, e.g., `__per_step__: true`, to indicate that the properties listed in the schema **SHOULD** be saved under each step in the state saver
   * If flag is not set, i.e., `__per_step__` key not in schema or `__per_step__: false`, the properties listed in the schema **SHOULD NOT** be saved under each step in the state saver, but **SHOULD** be saved in the `microdrop dump` export

[1]: http://json-schema.org/

**Comment by Lucaszw** [comment]
Some updates:

1. Have a ui with steps on left, tabs on top for each plugin.
2. Only one schema per plugin, with each key having a property "per_step" (see [4904147e](https://github.com/sci-bots/microdrop-3/commit/4904147ee3004fba7b3abef24ecc96b11b793668#diff-356e65406f11570a70ac6a03722191e5R204))
3. Have global variables as drop in alternatives for json editor (ie val is: $variable_name), to make it easier to change properties across many steps
4. Hide keys in json editor that are surrounded by double underscores (ie _ _ hidden_var _ _ ), see also #60
