### ISSUE TITLE
feat(selection): enable right-click selection menu items

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#43]
When a user right clicks on an electrode, MicroDrop displays context menu with the items: `Select Electrode: Shift-Click` and `Select Route: Alt-Click`. These menu items are currently disabled and act as a tooltip/hint reminding users of the context keys for selecting routes vs electrodes:

![image](https://user-images.githubusercontent.com/387220/37622419-ee77babe-2b97-11e8-870e-b4396c5f6896.png)

This requires users to click again (to close the menu), then use the keyboard shortcut + click to make their selection. I propose that we enable these menu items so that a user can right click on an electrode/route, then choose `Select Electrode: Shift-Click` or `Select Route: Alt-Click` to distinguish what they are trying to select.

Additionally, I think we should only show these context menu items when they are relevant; i.e., only show the `Select Route: Alt-Click` item when the user right-clicks on an electrode that contains a route. This should simplify the menu options and make the UI less confusing.

**Comment by Lucaszw** [comment]
I added this in commit 3484a2424067a600d7c5e2621ee1a325142af027. 

However I didn't implement the following feature:
"Additionally, I think we should only show these context menu items when they are relevant; i.e., only show the Select Route: Alt-Click item when the user right-clicks on an electrode that contains a route. This should simplify the menu options and make the UI less confusing."

The context menu / device ui plugin is unaware of (or at least should be) of the route-controller object; and to override the behaviour in a way that doesn't create a code-ratnest would probably require some sort of context-menu controller object that can be passed into various microdrop plugins and mqtt clients. This is something I have considered, and so perhaps this could be assigned to another PR feature request?
