### ISSUE TITLE
feat(installer): add auto-update to Electron app

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#44]
Test if compatible with:
 - [ ] `electron-packager`
 - [x] `asar` (ok if it's not compatible with `asar`, but it would just be nice to document it)
   * Looks like [maybe not](https://github.com/whitesmith/electron-asar-updater#how-it-works-read-this-first)

**Comment by Lucaszw** [comment]
AutoUpdater support added (moved to Electron Builder)
