### ISSUE TITLE
chore(ui): rename fields

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#47]
# Main menu

* [x]  Rename the "Show" menu to "View"

# Device view controls

* [x]  Rename "device" to "camera".
* [x]  Change "display_anchors" to displayAnchors.

# UI plugins

* [x]  All of the UI plugins have a "-plugin" suffix, except for "selected-ui". Rename it for consistency.

**Comment by cfobel** [comment]
@Lucaszw Please reference the commit where this was fixed.

**Comment by Lucaszw** [comment]
67f4a0e317c9b57011c4fe59d8dd8e4b5a8b0b4b
