### ISSUE TITLE
bug(device-ui): select route from right-click menu not working

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#48]
Version 1.1.51

# Steps to reproduce

1. Draw a route.
2. Right click on it (as soon as the mouse enters the "right-click" menu, the route turns yellow").
3. Choose "Select Route (Alt Click)" from the right-click menu.

# Result

The route (which was yellow after step 2), goes back to it's original blue color.

# Expected behaviour

The route should be highlighted in yellow.

# Note

Holding down "Alt" and clicking on a route also doesn't work.

**Comment by Lucaszw** [comment]
I will look into this.

To help with the debugging process, try launching the application through cmd.exe / powershell (https://github.com/sci-bots/microdrop-3/wiki/Debugging-App-Releases). And copy and paste the log with the issue.

**Comment by cfobel** [comment]
@Lucaszw Please reference the commit where this was fixed.

**Comment by Lucaszw** [comment]
d2c29d1a46121f4b37a53b8d709216fb4dcbd330
