### ISSUE TITLE
chore(updater): use github app API token to avoid API rate limit issues

### ISSUE THREAD

**Issue by Lucaszw** [sci-bots/microdrop-3.0#49]
GitHub Releases can make out quickly since any checkUpdates call from Electron makes 3 requests.

**Comment by Lucaszw** [comment]
More of a comment, closing for now

**Comment by cfobel** [comment]
This issue was created due to the GitHub API rate limt being exceeded by the AutoUpdater (causing it to fail) after 60 calls.

**Comment by Lucaszw** [comment]
I opened this initially because i didn't realize what was causing this. Waiting a few seconds seems to be fine
