### ISSUE TITLE
feat(state): brainstorm UI design ideas to simplify viewing/editing state

### ISSUE THREAD

**Issue by Lucaszw** [sci-bots/microdrop-3.0#50]
# Problem

During user testing at the Wheeler lab, users found the JSON editor confusing.

In this issue, collect ideas for simplifying the UI for viewing/editing state:

 - JSON editor:
   * [x] Hide fields that are not editable by the user (electrode `'translation'` and `'shape'` are hidden explicitly in [0b8a8ce0](https://github.com/sci-bots/microdrop-3/commit/0b8a8ce07f6295be7a8dc2bdfbe2df03de9deb51#diff-945ce736e74e398349660de76beaf3d5R115))
     - [x] See #60 for proposed more general solution.
 - [x] Separate Schema UI Plugin into: "Global UI Plugin" & "Step UI Plugin" (see #54)

**Comment by cfobel** [comment]
How was this resolved?

**Comment by Lucaszw** [comment]
I hid the fields (asides uuid). Mostly: I think this issue isn't specific enough. More created for documentation purposes

**Comment by cfobel** [comment]
Until this is resolved, I think this should remain open.  Perhaps it can act as a common point to link to issues that implement features that aim to address this overarching issue.
