### ISSUE TITLE
feature(ui): make separate scroll bar for step list

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#51]
The step list should have an independent scroll bar so that you can scroll through a long list off steps independently of the JSON properties on the right of the widget:

![image](https://user-images.githubusercontent.com/387220/37992556-1b647254-31da-11e8-9a95-c154cf52b684.png)

**Comment by cfobel** [comment]
@Lucaszw please reference the commit that this was implemented

**Comment by Lucaszw** [comment]
1540db53e527fb2e66f0d4189dd8c9ce1ef06ffc
