### ISSUE TITLE
feature(ui): buttons

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#52]
# Protocol/Recipe buttons

![image](https://user-images.githubusercontent.com/387220/37992759-a6d4a958-31da-11e8-81f5-8f6e96bc09bf.png)

* [x] Change the middle button tooltip (currently says "Save") to "Open".
* [x] Change the middle button to something that looks more like "Open/Browse", e.g., ![image](https://user-images.githubusercontent.com/387220/37993878-e163ae7c-31dd-11e8-9f2d-b4898a73a2cb.png)

Is there a way to stop/pause a running protocol?

**Comment by cfobel** [comment]
@Lucaszw please reference the commit that this was implemented.

**Comment by Lucaszw** [comment]
1540db53e527fb2e66f0d4189dd8c9ce1ef06ffc
