### ISSUE TITLE
feat(schema): add (optional) `hidden` property to schema fields

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#60]
It is useful to be able to optionally hide certain schema fields to simplify the UI as much as possible, similar to _hidden files_.  Electrode `'translation'` and `'shape'` are hidden **_explicitly_** in [0b8a8ce0](https://github.com/sci-bots/microdrop-3/commit/0b8a8ce07f6295be7a8dc2bdfbe2df03de9deb51#diff-945ce736e74e398349660de76beaf3d5R115) by hard-coding the hidden field names.

# Proposed solution

 - [x] Add an _optional_ `hidden` property to schema fields that indicate that corresponding values should be hidden in the editor UI.
 - [x] Add global option to force showing of hidden values in the editor UI, similar to `"show hidden files"` in Windows

**Comment by Lucaszw** [comment]
3ff057fa90c92ae6bbdedf9e2cd8b8ecda707206
