### ISSUE TITLE
feat(ui): only display plugins in StepUIPlugin and GlobalUIPlugin that contain step and global schema properties, respectively

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#62]
As of 85ef214fdeeba0ac655d3b8a88b5bc9f3f53542d:

 - the plugins displayed in the `StepUIPlugin` plugin [are hardcoded](https://github.com/sci-bots/microdrop-3/blob/85ef214fdeeba0ac655d3b8a88b5bc9f3f53542d/packages/step-ui-plugin/src/step-ui-plugin.js#L38-L40)
 - the plugins displayed in the `GlobalUIPlugin` plugin [are hardcoded](https://github.com/sci-bots/microdrop-3/blob/85ef214fdeeba0ac655d3b8a88b5bc9f3f53542d/packages/global-ui-plugin/src/index.js#L24-L29)

-----------------------------------------------

# Proposed feature

Only display those plugins in the `StepUIPlugin` and the `GlobalUIPlugin` which contain **step** and **global** schema properties, respectively.  For example, the `routes-controller` has no **global** properties and the `device-ui-plugin` has neither **step** nor **global** properties (no schema at all).

**Comment by Lucaszw** [comment]
4534fb9830c2a682135bf82327ad619f28bdba94
