### ISSUE TITLE
test(cpu-usage): test CPU load under various framerates

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#65]
I.e., throttle `request_animation_frame` and build a table with FPS and CPU load columns.

**Comment by Lucaszw** [comment]
Here is a chart (i did the tests in a random order, throttling animate() using:
// Always run (ran twice) [CPU 52%  , 54%]
if( Date.now() % 2 == 0) return; // [CPU 28.5%]
if( Date.now() % 4 == 0) return; // [CPU 16%]
if( Date.now() % 8== 0) return; // (ran twice) [CPU 12%, 13% ]
