### ISSUE TITLE
chore(plugins): make tab titles human-friendly

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#67]
For example, the `-ui-plugin` suffix could be stripped, underscores replaced with spaces, etc.

**Comment by Lucaszw** [comment]
4f130ec99fa11e4a2fa9ebf5b03b23919a444be8

**Comment by cfobel** [comment]
This should also be applied to the JSON editor tabs as well.  For example, `electrode-controls` could be `"Electrode controls"`.

**Comment by Lucaszw** [comment]
c33d49395c0a55d196337a4c9bcccdf53c3ed89f
