### ISSUE TITLE
feat(electrodes-plugin): add mechanism to await on to execute trigger

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#68]
![20180402_154643](https://user-images.githubusercontent.com/823355/38219522-fcd4240a-36a3-11e8-922b-be306decbe4e.jpg)

**Comment by Lucaszw** [comment]
5e99d934644646d5e2e12a33eac05aef7c0be276

**Comment by Lucaszw** [comment]
e6561dbd84ab02802f028dd43abb8e1010d51f79
