### ISSUE TITLE
feat(electron-debug): consider adding Electron DevTools to packaged executable

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#7]
By default, DevTools are not included with packaged Electron executable files.

However, they can be explicitly included by adding the following line to `packages/application/index.js`:

```javascript
require('electron-debug')({enabled: true});
```

[1]: https://github.com/sci-bots/microdrop-3/blob/master/packages/application/index.js

**Comment by Lucaszw** [comment]
Added electron-debug to @microdrop/application
