### ISSUE TITLE
feat(device-ui-plugin/electrode-controls): separate right-click route state

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#72]
- On **right-click**:
   * do not publish to any MQTT endpoint
   * change colour of affected electrodes to, e.g., **yellow**
 - On **select route** (from **right-click** context menu):
   * set MQTT `selected-routes` endpoint
   * change colour of **selected** electrodes to **red** (to match the **selected** electrode convention)

**Comment by Lucaszw** [comment]
3fccd5fee769d575b1e6f7211629998416254116
