### ISSUE TITLE
chore(schemas): change schema property names from camelCase to hyphen-separated

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#75]
Currently, some field names are labelled **camelCase** (e.g., `repeatDurationSeconds`) and others are labelled **hyphen-separated** (e.g., `selected-routes`).

Change all camelCase schema property names to hyphen-separated to keep things consistent.

**Comment by Lucaszw** [comment]
c6c2d0dfcb22b9b33d70cee8197a967ea10c5f8e
