### ISSUE TITLE
style(ui): naming, menu reorganization

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#82]
Some suggestions for naming, etc. to make things more clear:
* [x] Change "Clear Routes" and "Execute Routes" context menu items to "Clear All Routes" and "Execute All Routes"
* [ ] Remove "Change Device" from the right-click context menu (this is now available in the main menu)
* [x] Rename "Show" menu to "View" (I think this is a more common convention)
* [x] Move "Open Dev Tools" from the Help Menu to the "View" menu and rename to "Dev tools"
* [x] Change "transition-duration-milliseconds" to ""transition-duration-seconds"

**Comment by Lucaszw** [comment]
" Remove "Change Device" from the right-click context menu (this is now available in the main menu)" 
: The menu is only available when running through electron, so removing it from the context-menu wouldn't allow for changing devices if we choose to eventually serve up the ui as a URL for raspberry pi, or via a jupter notebook / lab widget.

**Comment by Lucaszw** [comment]
31ba38fd1c85f4f37f988b97084d28e63a9a9969
