### ISSUE TITLE
feat(ui): bring "Step" or "Global" widget to the foreground when users select and Electrode or Route

### ISSUE THREAD

**Issue by ryanfobel** [sci-bots/microdrop-3.0#84]
Choosing "Select Electrode" or "Select Route" from the right-click context menu opens the "Global/electrode controls" or "Step/route controls" JSON editor, but it doesn't bring the "Step" or "Global" widget to the foreground. Is it possible to implement that? Otherwise, the user is unlikely to see that the their selection had any effect if the affected widget is in the background.

**Comment by Lucaszw** [comment]
eb7dde10bf304d56d3dfd7b00d31437eac713504
