### ISSUE TITLE
bug(ui): `Help > Reset` does not clear all local storage state

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#85]
For example, after activating `Help > Reset`, the UI layout and video transform remain intact:

![image](https://user-images.githubusercontent.com/823355/38742268-1441725a-3f0a-11e8-9f2f-5146b65ea24b.png)

# Cause

@Lucaszw says this is because the main UI page (unexpectedly) has a separate local storage from the electron browser window processes.

# Proposed solution

Figure out a way to clear the main UI local storage as well.

**Comment by Lucaszw** [comment]
686d20a87af723b3d0da093db7c1c1ad29fa65e9
