### ISSUE TITLE
bug(global-ui-plugin): toggling `show-hidden` does not take effect until tab is changed in `step-ui-plugin` widget

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#86]
# Setup

 1. `show-hidden` set to `true`.  Note that routes model `routes[].path` entries are visible in the `step-ui-plugin` widget.
   ![image](https://user-images.githubusercontent.com/823355/38743575-726a8698-3f0d-11e8-871f-1a976674cfe8.png)

 2. Toggle `show-hidden` to `false`.  Note that routes model `routes[].path` entries are **_still_** visible in the `step-ui-plugin` widget.
   ![image](https://user-images.githubusercontent.com/823355/38743567-6da38d9e-3f0d-11e8-9ce7-3727fd70bd4e.png)

# Observations

The `step-ui-plugin` widget updates as expected after switching to a different tab and back again _within_ the `step-ui-plugin` widget.

 1. Routes model `routes[].path` entries are **_still_** visible in the `step-ui-plugin` widget after setting `show-hidden` to `false`.
    ![image](https://user-images.githubusercontent.com/823355/38744344-93671a62-3f0f-11e8-9569-caaeb0caf093.png)
 2.  Select other tab within `step-ui-plugin` widget
    ![image](https://user-images.githubusercontent.com/823355/38744363-a1d223b2-3f0f-11e8-87ea-2375640900c1.png)
 3.  Select the `route model` tab within `step-ui-plugin` widget
    ![image](https://user-images.githubusercontent.com/823355/38744388-b44134a2-3f0f-11e8-8e3d-c7f4067ef0f1.png)

**Comment by Lucaszw** [comment]
5080b03f4dbdb9c2fc70fdf0eb20743c07362d22
