### ISSUE TITLE
feat(ui): disable closing of UI plugin widgets

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#87]
As of 1.1.66, UI plugin widgets can be closed, but there is no way to reopen them without restarting MicroDrop.

For example, see the `Step` widget closed with no way of opening it again:

![microdrop-3-1 1 66-close-ui-widget](https://user-images.githubusercontent.com/823355/38745008-618fc8ac-3f11-11e8-907d-3d80d1a9e85a.gif)

**Comment by Lucaszw** [comment]
29889de8147c41e8152928b64d36c98dd080499a
