### ISSUE TITLE
feat(storage): provide an upgrade path for plugin data

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#88]

**Comment by Lucaszw** [comment]
I added a version manager to to upgrade plugins. However at the moment it doesn't update protocols automatically (you need to upload a microdrop protocol, preform the upgrade, and then re-download). Secondly, it uses plugin instances for upgrading and thus doesn't work for ui plugins unless the ui is loaded. 

I will close this issue and create two separate issues accordingly.

**Comment by cfobel** [comment]
Sounds great.  Thanks, Lucas!
