### ISSUE TITLE
feat(electron/local-storage): add mechanism to clear/reset local storage

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#9]

**Comment by Lucaszw** [comment]
You can now reset using `yarn run start --reset`

**Comment by cfobel** [comment]
~~This should also be possible through the command line interface to MicroDrop.~~

Implemented as a command-line argument to [`packages/application/bin/microdrop`][1] in c231e3bcc0b71eb3c2b702c8e570c52a93c8f7bb.

See also #12.

[1]: https://github.com/sci-bots/microdrop-3/blob/c231e3bcc0b71eb3c2b702c8e570c52a93c8f7bb/packages/application/bin/microdrop
