### ISSUE TITLE
bug(routes): make last transition behaviour consistent during execution of routes with different lengths

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#93]
# Setup

 1. Create a step at the end of the current protocol.
 2. Draw two or more routes of different lengths.
 3. Execute protocol.

# Expected behaviour

 1. Protocol executes all routes concurrently.
 2. Protocol finishes execution and **each electrode** corresponding to the
    **last transition in a route** is either:
      - **actuated**
      - **_not_ actuated**

# Observed behaviour

 1. Protocol executes all routes concurrently.
 2. Protocol finishes execution and **_only_ the electrode** corresponding to
    the last transition in **the _longest_ route** is **actuated**.

# Proposed fix

When a protocol finishes execution, either set **_all_ electrodes** corresponding to the **last transition in _any_ route** to either:
      - **actuated**
      - **_not_ actuated**

**Comment by Lucaszw** [comment]
ff165ab99bd559316380c1caa1a537ba4266506a
