### ISSUE TITLE
feat(routes): change `Execute` button to `Stop` during route execution

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#94]
As of 75896a966673f5928521910f96deeef45d1ba58f, if a **route is executed** from the **device plugin context menu** there is no (obvious) way to stop execution of the route.

# Proposed fix

 - Change `Execute` button to `Stop` during route execution when a **route is executed** from the **device plugin context menu**
 - Stop route execution when `Stop` is clicked

**Comment by Lucaszw** [comment]
779f3916142fb026f4a9ee9b386e7d24388297a9
