### ISSUE TITLE
feat(step-ui-plugin): disable step buttons during execution

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#95]
As of 75896a966673f5928521910f96deeef45d1ba58f, a user may click on a step button while a protocol is executing.  However, it is not clear what the behaviour should be when one does so.

# Proposed fix

Disable step buttons during execution to avoid any confusion.

**Comment by Lucaszw** [comment]
38dea97f7142f7d84db2875e48ba55f85340308b
