### ISSUE TITLE
feat(device-ui-plugin): add support for touch screens

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#96]
As of 1.1.69, the device-ui does not respond to touch events, i.e., you can’t toggle electrode actuation nor draw a path.

# Proposed solution

Add support to:

 - Toggle electrode state with touch tap
 - Draw routes (maybe _long press_ and drag?)

**Comment by Lucaszw** [comment]
This is a limitation from Threex.domeEvents: https://github.com/jeromeetienne/threex.domevents/issues/11
